blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)



class Post(models.Model):
    
    #статус публикации
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'  
    #поля
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                            choices=Status.choices,
                            default=Status.DRAFT)
    author = models.ForeignKey(User,
                            on_delete=models.CASCADE,
                            related_name='blog_posts')
    
    
    #менеджеры
    tags = TaggableManager()
    objects = models.Manager()
    published = PublishedManager()
    
    
    #метаданные
    class Meta:
        ordering = [
            '-publish'
        ]
        indexes = [
            models.Index(fields=['-publish'])
        ]
    
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                    args=[self.publish.year,
                        self.publish.month,
                        self.publish.day,
                        self.slug])
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post,
                            on_delete=models.CASCADE,
                            related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = [
            'created'
        ]
        indexes = [
            models.Index(fields=['created'])
        ]
    
    def __str__(self):
        return f"Комментарий от {self.name} к посту {self.post}"

blog/forms.py
import email
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                            widget=forms.Textarea)



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'name', 'email', 'body',
        ]


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from re import search
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import render, get_object_or_404

from .forms import EmailPostForm, CommentForm, SearchForm
from .models import Post, Comment
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
from django.views.generic import ListView
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
# Create your views here.


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # количество постов на странице 3
    paginator = Paginator(post_list, 3)
    # берет номер страницы, если нет то берет страницу 1
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # елси page_number не int то выдает страницу 1
        posts = paginator.page(1)
    except EmptyPage:
        #последняя страница
        posts = paginator.page(paginator.num_pages)
    return render(request,
                'blog/post/list.html',
                {'posts': posts, 'tag': tag},)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                            status=Post.Status.PUBLISHED,
                            slug=post,
                            publish__year=year,
                            publish__month=month,
                            publish__day=day,)
    # список комментариев 
    comments = post.comments.filter(active=True)
    # форма для комментариев 
    form = CommentForm()
    
    # список похожих постов
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    
    return render(request,
                    'blog/post/detail.html',
                    {'post': post, 'comments': comments, 'form': form, 'similar_posts': similar_posts})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post,
                            id=post_id,
                            status=Post.Status.PUBLISHED)
    comment = None
    # комметарий отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # создаем обьект класса Comment, не сохраняя его в БД
        comment = form.save(commit=False)
        # назначение поста для комментария
        comment.post = post
        # сохранение комментария
        comment.save()
    return render(request,
                'blog/post/comment.html',
                {'post': post, 'fomr': form, 'comment': comment})



def post_share(request, post_id):
    post = get_object_or_404(Post,
                            id=post_id,
                            status=Post.Status.PUBLISHED)
    sent = False
    
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} рекомендовал вам пост {post.title}"
            message = f"Прочтите пост {post.title} по ссылке {post_url}\n\n"
            # отправка email
            send_mail(subject, message, 'django.test@internet.ru', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request,
                'blog/post/share.html',
                {'post': post, 'form': form, 'sent': sent})



def post_search(request):
    # поиск
    form = SearchForm()
    # поисковой запрос
    query = None
    results = []
    
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            
            # results = Post.published.annotate(
            #     similarity=TrigramSimilarity('title', query),
            # ).filter(similarity__gt=0.1).order_by('-similarity')  
            
            search_vector = SearchVector('title', weight='A', config='russian') + SearchVector('body', weight='B', config='russian') # поля в которых будет производится поиск
            search_query = SearchQuery(query, config='russian') # поискововй запрос
            #результат поиска. создаются дополнительные поля search и rank
            results = Post.published.annotate(search=search_vector,
                                            rank=SearchRank(search_vector, search_query)
                                            ).filter(ranl__gre=0.3).order_by('-rank')
    
    return render(request,
                'blog/post/search.html',
                {'form': form, 'query': query, 'results': results})

blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}


{% block title %}
    Добавить комментарий
{% endblock title %}


{% block content %}
    
    {% if comment %}
        <h2>Ваш комментарий добавлен</h2>
        <p><a href="{{post.get_absolute_url}}">
            Вернуться к посту
        </a></p>
    {% else %}
        {% include 'blog/post/includes/comment_form.html' %}
    {% endif %}
{% endblock content %}
    

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load custom_tags %}


{% block title %}
    {{ post.title }}
{% endblock title %}


{% block content %}
    <p class="date">
        Опубликовано {{ post.publish }} | {{ post.author }}
    </p>
    {{ post.body|markdown}}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Поделиться
        </a>
    </p>

    <h2>Похожие посты</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
        </p>
        {% empty %}
            Похожих постов нет
    {% endfor %}
        

    
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} {{total_comments|ru_plural:"Комментарий,Комментария,Комментариев"}}
        </h2>
    {% endwith %}

    
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Комментарий {{ forloop.counter }} от {{comment.name}} {{comment.created}}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
            <p>Комментариев пока нет</p>
    {% endfor %}
    {% include 'blog/post/includes/comment_form.html' %}
{% endblock content %}
    

blog/templates/blog/post/latest_post.html
<ul>
    
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load custom_tags %}


{% block title %}
My Blog
{% endblock title %}


{% block content %}
    <h1>My blog</h1>
    {% if tag %}
        <h2>Посты с тегом {{tag.name}} </h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{post.get_absolute_url}}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
                
        </p>
        <p class="date">
            Опубликовано {{ post.publish }} | {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include 'pagination.html' with page=posts %}
{% endblock content %}
    

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load custom_tags %}


{% block title %}
    Поиск
{% endblock title %}



{% block content %}
    
    {% if query %}
        <h1>Посты содержащие {{ query }}</h1>
        <h3>
            {% with results.count as total_results %}
                Найдено {{ total_results }} {{total_results|ru_plural:"пост,поста,постов"}}
            {% endwith %}
        </h3>
        
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
            {% empty %}
            <p>Не найден постов по вашему запросу: {{ query }}</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}"> Искать снова </a></p>
        {% else %}
            <h1>Поиск постов</h1>
            <form method="get">
                {{ form.as_p }}
                <input type="submit" value="Search">
            </form>
    {% endif %}
{% endblock content %}
    

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}


{% block title %}
    Поделиться постом
{% endblock title %}


{% block content %}
    {% if sent %}
        <h1> E-mail успешной отправлен</h1>
        <p>
            "{{ post.title }}" пост успешной отправлен {{form.cleaned_data.to}}
        </p>
    {% else %}
    <h1> Поделиться постом {{ post.title }} по E-mail </h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Отправить по E-mail">
    </form>
    {% endif %}
{% endblock content %}